### ISSUE TITLE
 failed:Load model checkpoints\wav2lip_gan.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by honghaifeng** [instant-high/wav2lip-onnx-256#1]
python -W ignore inference_onnxModel.py --checkpoint_path "checkpoints\wav2lip_gan.onnx" --face "D:\some.mp4"

这个wav2lip_gan.onnx在哪里能下载到呀？
Traceback (most recent call last):
  File "inference_onnxModel.py", line 269, in <module>
    main()
  File "inference_onnxModel.py", line 238, in main
    model = load_model(device) # load wav2lip.onnx
  File "inference_onnxModel.py", line 63, in load_model
    session = onnxruntime.InferenceSession(model_path, sess_options=session_options, providers=providers)
  File "C:\Users\mrstage\anaconda3\envs\wav2lip_onnx\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\mrstage\anaconda3\envs\wav2lip_onnx\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from checkpoints\wav2lip_gan.onnx failed:Load model checkpoints\wav2lip_gan.onnx failed. File doesn't exist

改成wav2lip_gan.pth报这个错
Traceback (most recent call last):
  File "inference_onnxModel.py", line 269, in <module>
    main()
  File "inference_onnxModel.py", line 238, in main
    model = load_model(device) # load wav2lip.onnx
  File "inference_onnxModel.py", line 63, in load_model
    session = onnxruntime.InferenceSession(model_path, sess_options=session_options, providers=providers)
  File "C:\Users\mrstage\anaconda3\envs\wav2lip_onnx\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\mrstage\anaconda3\envs\wav2lip_onnx\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from checkpoints\wav2lip_gan.pth failed:Protobuf parsing failed.

**Comment by instant-high** [comment]
Sorry, copy and paste from another repo error.... my fault

Download wav2lip_256.onnx from releases to 'checkpoints' folder and change the commandline this way:

--checkpoint_path "checkpoints\wav2lip_256.onnx"


You can indeed also run the 96x96 models wav2lip.onnx and wav2lip_gan.onnx with the same script, but you have to
download the two files from my wav2lip_onnx repo link. 
Then you have to use --checkpoint_path "checkpoints\wav2lip.onnx" or --checkpoint_path "checkpoints\wav2lip_gan.onnx"
